default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: 123456
  host: a54489o505.goho.co 
  port: 43270

test:
  <<: *default
  database: greentestmini_test

development:
  <<: *default
  database: greentestmini

production:
  <<: *default
  database: greentestmini
